
spring:
  datasource:
    jdbc-url: jdbc:mysql://172.17.11.203:3306/db1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver

    primary: 
      jdbc-url: jdbc:mysql://172.17.11.203:3306/db1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: mysql
      driver-class-name : com.mysql.jdbc.Driver

    secondary: 
      jdbc-url: jdbc:mysql://172.17.11.203:3306/db2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: mysql
      driver-class-name : com.mysql.jdbc.Driver
            
mybatis:
  mapper-locations: classpath:mapper/def/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: org.tacos.mybatis.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  