spring:
  #main:
    #allow-bean-definition-overriding: true
  datasource:
    # driver-class-name: 
    schema: classpath:db/schema.sql # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    data: classpath:db/data.sql     # data.sql中一般是DML脚本，即通常为数据插入脚本      
    username: sa
    password: 
    url: jdbc:h2:mem:testdb # 缺省
    initialization-mode: ALWAYS
    driverClassName: org.h2.Driver
    
    #第1个数据库信息
    ds1:
      jdbc-url: jdbc:mysql://172.17.11.203:3306/db1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: mysql
      driverClassName: com.mysql.jdbc.Driver
    #第2个数据库信息  
    ds2:
      jdbc-url: jdbc:mysql://172.17.11.203:3306/db2?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: mysql
      driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    root: debug
    #type: com.zaxxer.hikari.HikariDataSource
    #type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    generate-ddl: true
#    database: h2
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #database-platform: org.hibernate.dialect.MySQL5Dialect