server:
  port: 8081
logging:
  level:
    springboot.redis.lock: debug
    org.springframework.web: debug


#Redisson 基于Springboot
spring:
  redis:
      # Redis 数据库索引（默认为 0）
      database: 0
      # Redis 服务器地址
      host: 172.17.12.166
      # Redis 服务器连接端口
      port: 6379
      password: ocmomp
      timeout: 10s
      lettuce:
          pool:
              #连接池最大连接数（使用负值表示没有限制） 默认 8
              max-active: 50
              #连接池中的最大空闲连接 默认 8
              max-idle: 8
              #连接池中的最小空闲连接 默认 0
              min-idle: 0

      

#spring.redis.cluster.nodes=${redis.nodes}


              
#需要注意的是，以上配置中的lettuce是指使用Lettuce作为Redis客户端的实现，Lettuce是一个高性能、线程安全的Redis客户端，相较于Jedis具有更好的性能和更完整的功能支持。如果不想使用Lettuce，可以使用以下配置：
#spring:
#  redis:
#    host: localhost # Redis服务器地址
#    port: 6379 # Redis服务器端口号
#    password: # Redis服务器密码，如果没有密码可以不填
#    database: 0 # Redis数据库编号，从0到15，默认为0
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数，默认为8
#        max-idle: 8 # 连接池中最大的空闲连接数，默认为8
#        min-idle: 0 # 连接池中最小的空闲连接数，默认为0
#        max-wait: -1ms # 连接池最大等待时间，-1表示无限等待，默认为-1ms
